name: 'clang-tidy-action'
description: 'Exports clang-tidy diagnostics to inline comments.'
author: 'asarium'
inputs:
  fixesFile:
    description: 'Path to the replacement file produced by -export-fixes'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
